<a href="https://colab.research.google.com/github/dharineeshramtp2000/Wine-Data-Classification-AdaBoost/blob/master/Male_Female_Voice_Predictor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import the Libraries

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Importing the Dataset. Here we use the dataset from [ML Data](https://www.mldata.io/datasets/).
![](https://www.goodfood.com.au/content/dam/images/h/1/5/t/q/e/image.related.wideLandscape.940x529.h17bz1.png/1541726361585.jpg)
---

Here we are going to determine the class of wine based on few independent variables.







In [2]:
Dataset = pd.read_csv("wine_weka_dataset.csv")
X = Dataset.iloc[:,:-1].values
y = Dataset.iloc[:,-1].values
Dataset.describe()

Alcohol  Malic acid  ...  OD280/OD315 of diluted wines      Proline
count  178.000000  178.000000  ...                    178.000000   178.000000
mean    13.000618    2.336348  ...                      2.611685   746.893258
std      0.811827    1.117146  ...                      0.709990   314.907474
min     11.030000    0.740000  ...                      1.270000   278.000000
25%     12.362500    1.602500  ...                      1.937500   500.500000
50%     13.050000    1.865000  ...                      2.780000   673.500000
75%     13.677500    3.082500  ...                      3.170000   985.000000
max     14.830000    5.800000  ...                      4.000000  1680.000000

[8 rows x 13 columns]

Lets Feature Scale the independent variables

In [0]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X = sc_X.fit_transform(X)

Splitting the dataset into training and testing and performing a good shuffle of data

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y , test_size = 0.3, random_state =42, shuffle = True)

Now lets define our Adaboost Classifier.
We know how trees work. We use these attributes in order to make the splits and finally make the prediction using the leaf values of the tree.
Instead of using normal trees, lets define it using boosting algorithm(**here Adaboost**)

![](https://www.frontiersin.org/files/Articles/284242/fnagi-09-00329-HTML/image_t/fnagi-09-00329-g001.gif)

Feel free to use the [Documnetaton for Adaboost Classifier](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.AdaBoostClassifier.html)

In [5]:
from sklearn.ensemble import AdaBoostClassifier
classifier = AdaBoostClassifier()
classifier.fit(X_train, y_train)


AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=1.0,
                   n_estimators=50, random_state=None)

Now lets predict with our test set

In [0]:
y_pred = classifier.predict(X_test)

Now lets evaluate the accuracy , F1 score and the Confusion Matrix in order to check how well our model is classifying new data

---

First lets see how model works with our tarining examples

In [7]:
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score
acc_train = accuracy_score(y_train, classifier.predict(X_train))
f1_train = f1_score(y_train, classifier.predict(X_train), average= 'weighted')

print("Traing set results")
print("ACCURACY ---------------------->",acc_train)
print("F1 SCORE ---------------------->",f1_train)

Traing set results
ACCURACY ----------------------> 0.9435483870967742
F1 SCORE ----------------------> 0.9436949059289295


Now lets see how well is our model. So now lets evaluate with our test set

In [8]:
acc_test = accuracy_score(y_test, y_pred)
f1_test = f1_score(y_test, y_pred, average= 'weighted')

print("Test set results")
print("ACCURACY ---------------------->",acc_test)
print("F1 SCORE ---------------------->",f1_test)

Test set results
ACCURACY ----------------------> 0.9259259259259259
F1 SCORE ----------------------> 0.9245135111801778


Confusion Matrix

In [9]:
cm = confusion_matrix(y_test,y_pred)
print(cm)


[[19  0  0]
 [ 0 11  3]
 [ 1  0 20]]


Our decision Tree has done well in predicting our Train as well as Test set. So it has made the **appropriate fitting**

Though, normal Random Forest works with greater accuracy in this case, it does not for all other cases. Hence for some datasets its important that we use Boosting Algorithms like Adaboost, XGboost etx..,
